name: Release
on:
  push:
    branches:
      - stable
      - dev
jobs:
  release:
    name: 📦 Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 7
          run_install: false
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GIT_AUTOR_NAME: "BlazingWorks CI"
          GIT_AUTOR_EMAIL: "hey@blazing.works"
          GIT_COMMITTER_NAME: "BlazingWorks CI"
          GIT_COMMITTER_EMAIL: "hey@blazing.works"
        run: pnpm semantic-release
